# Read the Docs configuration file
version: 2

# Specify the Conda environment
conda:
  environment: environment.yaml

# Build documentation using explicit commands
build:
  os: ubuntu-lts-latest
  tools:
    python: "3.10"  # Keep this for compatibility

  commands:
    - conda run -n picmol python -m sphinx -T -b html -d _build/doctrees docs $READTHEDOCS_OUTPUT/html

