# Read the Docs configuration file
version: 2

# Specify the Conda environment
conda:
  environment: environment.yaml

sphinx:
  configuration: docs/conf.py
  builder: html

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.10"
  python:
    install:
      - method: pip
        requirements: environment.yaml  # Point to your Conda environment file
        extra_pip_args:
          - --no-deps  # Tell pip not to install dependencies (Conda handles them)
