# Read the Docs configuration file
version: 2

# Specify the Conda environment
conda:
  environment: environment.yaml

sphinx:
  configuration: docs/conf.py
  builder: html

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.10"
  python:
    install: []