name: picmol
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - comm=0.2.2
  - debugpy=1.8.11
  - decorator=5.2.1
  - dftd4=3.7.0
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - gromacs=2024.4
  - importlib-metadata=8.6.1
  - ipykernel=6.29.5
  - ipython=8.33.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - libblas=3.9.0
  - libcxx=19.1.7
  - libedit=3.1.20191231
  - libffi=3.4.4
  - libgfortran5=14.2.0
  - liblapack=3.9.0
  - libopenblas=0.3.29
  - libsodium=1.0.20
  - llvm-openmp=19.1.7
  - matplotlib-inline=0.1.7
  - mctc-lib=0.3.2
  - multicharge=0.3.0
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.4.1
  - packaging=24.2
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.0
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.50
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - python=3.10.16
  - python-dateutil=2.9.0.post0
  - pyzmq=26.2.0
  - readline=8.2
  - setuptools=75.8.0
  - simple-dftd3=1.2.1
  - six=1.17.0
  - sqlite=3.45.3
  - stack_data=0.6.3
  - tblite=0.4.0
  - tk=8.6.14
  - toml-f=0.4.2
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xtb=6.7.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - pip:
    - contourpy==1.3.1
    - cycler==0.12.1
    - et-xmlfile==2.0.0
    - fonttools==4.56.0
    - kaleido==0.2.1
    - kiwisolver==1.4.8
    - matplotlib==3.10.1
    - mpltern==1.0.4
    - mpmath==1.3.0
    - narwhals==1.29.1
    - numpy==2.2.3
    - openpyxl==3.1.5
    - pandas==2.2.3
    - pillow==11.1.0
    - plotly==6.0.0
    - pyparsing==3.2.1
    - pytz==2025.1
    - rdkit==2024.9.5
    - scipy==1.13.1
    - sympy==1.13.3
    - tzdata==2025.1
    - git+https://github.com/TUHH-TVT/openCOSMO-RS_py