[project]
name = "picmol"
version = "0.0.3"
authors = [{name = "Allison Peroutka"},]
description = "a python package for phase Kirkwood-Buff theory and thermodynamic modeling for liquid-liquid equilibria calculations"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
  "Programming Language :: Python :: 3"
]
include_package_data=True,
package_data={'': ['data/*.csv', 'models/unifac_subgroups/*.csv', models/unifac_subgroups/*.tsv']}


[project.urls]
Homepage = "https://github.com/aperoutka/picmol"
